#!/bin/bash

# clear; 
# g++ -g -std=c++20 ./headers/point.hpp ./headers/DynamicDistribution.hpp ./source/DynamicDistribution.cpp ./source/point.cpp ./tests/Kleinberg_graph_test.cpp  -o ./res; 
 g++ -g -std=c++20 ./headers/PonomarenkoGraph.hpp ./headers/point.hpp ./source/point.cpp ./tests/figure_test.cpp ./headers/Figure.hpp ./source/Figure.cpp -o ./res; 
./res; 
# rm ./res;